# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('quantidade_devolver', models.IntegerField()),
                ('quantidade_atual', models.IntegerField()),
            ],
        ),
    ]
