# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=15),
        ),
    ]
