# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolucao', '0002_auto_20161004_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='quantidade_atual',
            new_name='quantidade_faltando',
        ),
    ]
